### ISSUE TITLE
Lien sur la démo (site WEB)

### ISSUE THREAD

**Issue by wrey75** [DSI-HUG/dejajs-components#106]
Sur la page https://dsi-hug.github.io/dejajs-components/, il y a un problème de lien: 

> @deja-js/component
> 
> This is the home for the Hôpitaux Universitaires de Genève - DSI - Domaine Patient team's Angular2 components for Angular 2 and material.
> 
> Online demo : https://dsi-hug.github.io/dejajs-components

Le lien devrait être *https://dsi-hug.github.io/dejajs-components/components/accordion*

**Comment by vapkse** [comment]
Is working as expected
