### ISSUE TITLE
Treelist border

### ISSUE THREAD

**Issue by rtrompier** [DSI-HUG/dejajs-components#124]
By default, the Treelist should not have a black border.
We have to override every time the treelist style (with a deep selector) to remove this border.

@vapkse @guerricm @Maxouhell What do you think ?

**Comment by vapkse** [comment]
Comme le bord est un truc assez deep et ne peut pas être mis facilement depuis l'extérieur, je peux créer un fichier scss 'tree-list-borders.scss', qu'on importe ou pas dans le projet en fonction de ce qu'on veux.

**Comment by vapkse** [comment]
Done
