### ISSUE TITLE
Dependence NGRX

### ISSUE THREAD

**Issue by rtrompier** [DSI-HUG/dejajs-components#284]
Hello,

Il faut prévoir la suppression de NGRX de la librairie.
Un utilisateur est actuellement obligé d'avoir NGRX dans son app pour pouvoir utiliser DEJAJS, alors qu'on l'utilise uniquement pour une démo.

**Comment by rtrompier** [comment]
L'autre solution serait de dédoubler le package.json de la demo.
Actuellement la demo et la lib partage le meme package.json. Il faudrait que chaque app est son propre package.json pour éviter ce genre de problème.

**Comment by vapkse** [comment]
Done in >3.0.0-beta.0
