### ISSUE TITLE
Dependence json-object-mapper

### ISSUE THREAD

**Issue by rtrompier** [DSI-HUG/dejajs-components#285]
Supprimer json-object-mapper des dépendances de DEJAJS.
Un utilisateur est actuellement obligé d'avoir json-object-mapper dans son app pour pouvoir utiliser DEJAJS, alors qu'on l'utilise uniquement pour une démo.

De plus, son utilisation n'est plus utile car HttpClient permet maintenant de typer l'objet retourné par le service.

**Comment by vapkse** [comment]
Done in @deja-js/component 3.0.0-beta.4
