### ISSUE TITLE
Gestion des dépendances incorrect

### ISSUE THREAD

**Issue by rtrompier** [DSI-HUG/dejajs-components#287]
Actuellement toute les dépendances sont en peerDependencies de la lib.
Ce qui oblige a l'utilisateur d'avoir toute les dépendances de dejajs dans son projet (Monaco, Prisme, etc ...)

Ces peerDependencies devrait etre des dependencies.
Par contre Angular, etc reste bien des dépendances.

**Comment by vapkse** [comment]
Done in @deja-js/component 3.0.0-beta.4
