### ISSUE TITLE
Bundle des fichier scss theming

### ISSUE THREAD

**Issue by rtrompier** [DSI-HUG/dejajs-components#288]
Actuellement on expose tout les fichier scss.
Il faut trouver une solution pour bundler les fichiers SCSS à exposer, pour n'avoir qu'un seul fichier dans le bundle (Ex: deja-js/component/_theming.scss)
Angular utilise : https://www.npmjs.com/package/scss-bundle, mais je ne parvient pas a importer les Material Theming lors du bundle.

### Supprimer les fichiers suivants : 
- _flex.scss
- _material.scss et ses enfants. (Y a t-il toujours une raison d'override Material)

### Déplacer dans DPI : 
- _form-validation.scss
- _colors.scss
- _palette.scss
- _themeHUG.scss

**Comment by vapkse** [comment]
Done in >3.0.0-beta.11
