### ISSUE TITLE
Modification chargement Font

### ISSUE THREAD

**Issue by rtrompier** [DSI-HUG/dejajs-components#290]
Ne plus charger les fonts via Sass qui a besoin de tilde importer pour trouver le chemin des fonts.

Il faut publier un fichier CSS qui charge les fonts dans DEJAJS Resources.

Ce fichier css doit alors etre chargé depuis le style de l'app (Angular CLI Styles) et non depuis un import SCSS dans l'application elle meme.

**Comment by Maxouhell** [comment]
ça va pas marcher.
Le chemin vers les font doit toujours être juste, voila pourquoi le tilde importer est efficace, car in importe toujours depuis ~(node_modules)/le_meme_chemin.scss

Mais si tu fais ça depuis un css, rien ne va plus, on sera bloqués car en fonction de l'app le chemin ne sera plus valide.

Peut être qu'il faut virer cet import de font par contre, c'est pas très catholique, et passer par un CDN (et en interne on se débrouilles avec les outils mis à disposition)

**Comment by vapkse** [comment]
Les fonts sont maintenant chargés dans dejajs-dpi, depuis dejajs-ressources, mais plus dans @deja-js/component. Dans la demo, les fonts sonts chargés depuis le web dans index.html.
Done in >3.0.0-beta.11
