### ISSUE TITLE
objectif/but de ce projet?

### ISSUE THREAD

**Issue by istiti** [DSI-HUG/dejajs-components#330]
Bonjour, excusez-moi de faire du bruit ici... par curiosité je me pose deux questions:
1. quel est l'objectif de ce repo? 
2. pourquoi DSI-HUG a crée ce projet ? 

Merci d'avance

**Comment by Maxouhell** [comment]
Bonjour,
Ce repo a été créé pour combler le manque de composants sur le web pour nos applications développés en interne.
L’objectif est de mettre open-source ces composants, car si nous en avons eu besoin, il est probable que d’autres projets en aient besoin eux aussi.
