### ISSUE TITLE
webpack+angular2

### ISSUE THREAD

**Issue by crystalwm** [DSI-HUG/dejajs-components#39]

**Comment by vapkse** [comment]
Can you describe the issue please?

**Comment by crystalwm** [comment]
I have seen you code using the webpack+material and it works.Thanks o lot for you help
I have asked a question on stackoverflow [webpack-angular-material2-template-parser-error](http://stackoverflow.com/questions/42926045/webpack-angular-material2-template-parser-error)
I try to use the demo on the [material.angular.io](https://material.angular.io/components/component/radio) and the original example here [material-radio](https://plnkr.co/edit/RLLp76A8bifrhn9oUzCK?p=preview).
I write [the demo](https://github.com/crystalwm/plunker-demo-angular-material2-radio) as the material doc. I found a werid thing.So I think the current material version is unstable. Maybe I should try it later.


in the normal network speed. the page is abnormal and show error message on the console.

in the Good 3G network speed.(use the chrome developer tools to limit the network speed) it works.
