### ISSUE TITLE
Impossible de changer l'heure + minute du Datepicker 

### ISSUE THREAD

**Issue by rtrompier** [DSI-HUG/dejajs-components#78]
Il est impossible de changer les heures + les minutes du datepicker.
Si je change l'heure, puis les minutes, les heures sont réinitialisées.
Idem si je change d'abord minutes puis les heures, les minutes sont reset ...

**Comment by Maxouhell** [comment]
C'est juste un bug dans la demo-app, il y a le même model pour deux date-picker, et ça pose des conflits.

**Comment by rtrompier** [comment]
Ok cool, tu as fixé sur la dev du coup ?
